import React, { useState } from 'react';
import AlgorithmForm from './components/AlgorithmForm';
import NumberList from './components/NumberList';
import NumberChart from './components/NumberChart';
import './styles.css';
import './App.css' // Importar los estilos

function App() {
    const [numbers, setNumbers] = useState([]);
    const [selectedIndex, setSelectedIndex] = useState(null);

    const handleGenerate = async (algorithm, count, params) => {
        const formData = new FormData();
        formData.append('algorithm', algorithm);
        formData.append('count', count);
        Object.keys(params).forEach(key => {
            if (params[key]) {
                formData.append(key, params[key]);
            }
        });

        const response = await fetch('https://pseudo-random-numbers-generators.onrender.com/generate', {
            method: 'POST',
            body: formData
        });

        const data = await response.json();
        setNumbers(data);
        setSelectedIndex(null); // Reset selection on new generation
    };

    const handleSelect = (index) => {
        setSelectedIndex(index);
    };

    return (
        <div className="App">
            <h1>Random Number Generator</h1>
            <AlgorithmForm onGenerate={handleGenerate} />
            <main>
                <NumberList
                    numbers={numbers}
                    selectedIndex={selectedIndex}
                    onSelect={handleSelect}
                    itemsPerPage={10}
                />
                <NumberChart numbers={numbers} onSelect={handleSelect} selectedIndex={selectedIndex} />
            </main>
            <footer>Generated by FastAPI and React</footer>
        </div>
    );
}

export default App;
